name: psychology_ai_app
description: "AI-powered psychology therapy app with appointment scheduling and session management."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0

  # UI & Animations
  animate_do: ^3.1.2
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0

  # Calendar & Date/Time
  table_calendar: ^3.0.9
  intl: ^0.19.0

  # Chat UI
  dash_chat_2: ^0.0.18

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Audio/Voice (for future voice therapy sessions)
  speech_to_text: ^6.6.0
  flutter_tts: ^4.2.3

  # Notifications
  # flutter_local_notifications: ^16.3.0

  # Utils
  uuid: ^4.2.1
  timeago: ^3.6.0
  flutter_markdown: ^0.7.7+1

  # Image Handling
  image_picker: ^1.0.4

  # Icons & Fonts
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  flutter_webrtc: ^0.10.1
  camera: ^0.11.0+2
  google_mobile_ads: ^5.3.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/.env
